# Generated by Django 2.2 on 2019-10-11 18:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 11, 18, 25, 55, 7191, tzinfo=utc)),
        ),
    ]
